# 由source 指向 target
source_lidar_topic: /backscan
target_lidar_topic: /frontscan

source_lidar_frame: back_laser
target_lidar_frame: front_laser

icp_score: 5.386

# 在base_link坐标系下主雷达的坐标
main_to_base_transform_x: 1.7735
main_to_base_transform_y: -0.9235
main_to_base_transform_roll: 0.0 # 反装为负
main_to_base_transform_yaw: -0.785398
