# 由source 指向 target
source_lidar_topic: /back_scan  #根据实际点云topic填写
target_lidar_topic: /front_scan #根据实际点云topic填写

source_lidar_frame: back_laser  # frame_id
target_lidar_frame: front_laser # frame_id
source_frame: base_link         # frame_id

# icp_score: 5.386
icp_score: 8.0
fitness_score: 0.1

# 在base_link坐标系下主雷达的坐标
main_to_base_transform_x: 1.49090
main_to_base_transform_y: -0.58590
main_to_base_transform_roll: 0.0 # 反装为负
main_to_base_transform_yaw: -0.7853981

# 在base_link坐标系下主雷达的坐标
main_to_back_transform_x: -1.49090
main_to_back_transform_y: 0.58590
main_to_back_transform_roll: 0.0 # 反装为负
main_to_back_transform_yaw: 1.8683531

# 校准后的位姿
store_param_file: src/multi_lidar_calibration/config/calibrated_pose.yaml